name: manager_api
description: Manager GraphQL and Rest
version: 1.4.3
publish_to: 'none'
homepage:

environment:
  sdk: '>=3.5.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  graphql: ^5.2.3
  gql: ^1.0.1
  dio: ^5.9.0
  cross_file: ^0.3.5
  log_print: ^0.0.2
  web_socket_channel: 3.0.3
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
